[packages]
#
brew = [
    "wget",
    "pyenv",
    "pyenv-virtualenv",
    "pipx",
    "tree",
    "lsd",
    "tldr", # dev docs and manuals, e.g. `tldr pyenv`
    "node",
    "autojump",
    "fzf",
    "opencode",
    "uv",
    "pip-tools",
    "terminal-notifier",
]

cask = [
    "google-chrome",
    "devtoys",
    "iterm2",
    "jetbrains-toolbox",
    "pycharm",
    "webstorm",
    "fleet",
    "slack",
    "github",
    "logi-options-plus",
    "gimp",
    "zoom",
    "postman",
    "rectangle",
    "zed",
    "chatgpt",
    "superwhisper",
    "onedrive",
    "notion",
    "codex",
]
